### ISSUE TITLE
Issues with the start functionality

### ISSUE THREAD

**Issue by ibraghada** [snocks/Timer-AlaaZahra#3]
I think you have the cutest timer! (^_^)
but the issue is that each time I click the start button the start function gets called and the timer starts acting weird :D 

you would want to check it out and fix it. 
you may try to disable the start button when it gets clicked once, or figure something else out. But still cool job! :+1:

**Comment by zahraayman** [comment]
we fixed it,
thank you for your suggestion ^_^
